### ISSUE TITLE
Pointing to scenarios when calling Inro tools

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#11]
[e.g. Volume per Operator](https://github.com/TravelModellingGroup/TMGToolbox/blob/master/TMGToolbox/src/analysis/transit/strategy_analysis/volume_per_operator.py)
Lines 204/205:
```
matrixCalculator(self._CalcRidership(tempIntermediateMatrix.id, demandMatrixId), scenario=self.Scenario)
matrixAggregation(tempIntermediateMatrix.id, tempResultMatrix.id, agg_op="+")
```
There are some calls to Inro tools scattered throughout the code base that are missing scenario identification. For many tools, this failure is obvious and would have been rectified immediately. However, for matrix-related tools, a problem only arises when the active scenario is of a different zone system than the intended scenario. As a result, these mistakes have gone unnoticed for quite some time. It would be beneficial to do a complete sweep through all tools to find and fix instances where Inro tool calls are missing scenarios.

In the example above, line 204 is correctly done, but line 205 is not.

**Comment by mattaustin222** [comment]
Brendan,
The code I referenced above was only an example. There are other instances of this problem throughout the code base that should be updated. I don't feel that the issue should be consider closed.

**Comment by BrendanReilly** [comment]
Yes you are correct - thanks for noticing and re-opening this issue.
