### ISSUE TITLE
Extend Network Package format to include Aux. Transit Volumes

### ISSUE THREAD

**Issue by King-David** [TravelModellingGroup/TMGToolbox#12]
The walk volumes on links are a key QC parameter used by Metrolinx within PD 1, especially around Union station. Currently the auxiliary transit volumes are not exported with the NWP and I ask if this feature could please be added.

Thank you.

**Comment by BrendanReilly** [comment]
This has just been added to the most recent commit.

**Comment by PeterKucirek** [comment]
Thanks for taking care of this enhancement. I was going to make an attempt but I don't have the time this week. Just a couple of notes based on your latest commit:

`_batchout_traffic_results()`, where you've added the code to export the aux. transit volumes, only gets called when there are traffic results. So this could potentially fail if, say, the scenario has a transit assignment but not a traffic assignment

- You'll need to update `import_network_package.py` as well.

**Comment by BrendanReilly** [comment]
@PeterKucirek The most recent commit addresses the issues pointed out in your comment.
