### ISSUE TITLE
Import Network Package silently adds functions

### ISSUE THREAD

**Issue by PeterKucirek** [TravelModellingGroup/TMGToolbox#15]
I have a set of functions which continue to pollute my Emmebanks like a virus (and breaking my model) because the Import Network Package / Merge Functions tool silently adds new functions if they do not conflict with any in the existing Emmebank.

I propose that a checkbox / boolean flag be introduced to enable/disable this behaviour. For backwards-compatibility it would be turned ON by default.  

I can handle the change at the Python level but someone else is going to need to update the XTMF side as I don't have the time to set up a proper .NET IDE and working environment.

**Comment by BrendanReilly** [comment]
Hi @PeterKucirek  --

It looks as if you have already completed this on the XTMF side, is that correct?

Thanks

**Comment by PeterKucirek** [comment]
Nope. As I mentioned before, I haven't had the time to setup the XTMF developer environment so I can't make the change on the XTMF-side. I haven't pushed anything to the XTMF repo in a long time.

**Comment by BrendanReilly** [comment]
I've added the parameter on the XTMF side: "AddFunctions"

**Comment by mattaustin222** [comment]
@PeterKucirek et al (@bilalyusuf specifically):

It seems Bilal started the process for the AddFunctions by adding a placeholder on the Python side. Unfortunately, that breaks the call function when called from other tools (direct calls from XTMF are fine with Brendan's change as far as I can tell). Can we make that argument default to true on the python side? Or should I modify all affected tools?

**Comment by JamesVaughan** [comment]
ef68edfa should fix this.  I'll rebuild XTMF with this change.

**Comment by JamesVaughan** [comment]
You can now download the change (with XTMF) from http://tmg.utoronto.ca/XTMF.zip
