### ISSUE TITLE
Export network package tool does not export inboa and fiali node attributes

### ISSUE THREAD

**Issue by bryce-sharman** [TravelModellingGroup/TMGToolbox#192]
When performing a round-trip NWP export/import test, I noticed that the node transit result attributes `inboa` and `fiali` are not exported in the network package.

Looking at the function `_batchout_transit_results` in `src/input_output/export_network_package.py`, I can confirm that there is code to output transit segment and auxiliary transit results, but not these node results. This export (and corresponding import) can likely be handled in a similar fashion to how the existing results are stored.

---

For reference, here's the description of these attributes from the Emme Help:
Number of initial boardings (inboa) that occur at the node, for all its outgoing segments. For a regular node, this is the number of passengers that board a transit vehicle of the first line used on their trip. For a centroid, this result contains the number of outgoing auxiliary transit-only trips, that is, the number of travellers who use only auxiliary transit modes from the centroid to their destination. 

Number of final alightings (fiali) that occur at the node, for all its incoming segments. For a regular node, this is the number of passengers that alight from a transit vehicle of the last line used on their trip. For a centroid, this result contains the number of incoming auxiliary transit-only trips, that is, the number of travellers who use only auxiliary transit modes from their origin to the centroid.

**Comment by wdiogu** [comment]
@bryce-sharman What version of Emme are you using? Emme version 4.6.0 (my current version) with the import/export network packages of TMGToolbox1 are storing the node attributes result. 

If a network does not have a valid transit results, Emme does not add the inboa/fiali to the node attributes table.
