### ISSUE TITLE
V4 FBTA Walk Perception

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#21]
There appears to be a minor selection error in V4 FBTA (line 1014, etc.). Node 10000 (i.e. the lower end of the range) is excluded from the @walkp assignment and people are thus able to teleport across the connected links (there may be other problems as well).

**Comment by PeterKucirek** [comment]
@BrendanReilly @bilalyusuf any news on this bug?

**Comment by bilalyusuf** [comment]
the node ranges were actually clashing so it was assigning the right perception value when performing the network calculation but then in line 1020, it rewrote the node 10000 links to have a 0 walk perception. I have fixed the ranges so it shouldnt clash anymore.
