### ISSUE TITLE
Volume Per Operator yields infinite values

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#23]
Emme 4.3 now yields negative infinity across the diagonal when extracting strategy values from a strategy-based analysis (at least it does when I recreate the Volume per Operator analysis). In all cases in the model - except for one - the demand along the diagonal is zero. However, the airport model yields a non-zero intra-zonal transit demand in the airport zone, so the resulting ridership (i.e. the sum of strategy value matrix multiplied by demand matrix) yields negative 10^22 or so.

**Comment by JamesVaughan** [comment]
@mattaustin222 Which version of XTMF/TMG_Toolbox was used to produce this result?

**Comment by PeterKucirek** [comment]
This is a bug in Emme 4.3.2 that I caught last week. I contacted INRO and they are have acknowledged the bug; presumably they are working on a solution.

In the meantime in my code I am correcting negative infinity to 0 and reporting the number of cells changed. That may or may not work for you; it depends on your use case.

**Comment by mattaustin222** [comment]
@JamesVaughan 1.3.1177 (I downloaded it yesterday from the website)
@PeterKucirek Thanks Peter, I'm glad I'm not the only one with this issue.

**Comment by JamesVaughan** [comment]
@mattaustin222 We are currently implementing the fix as specified by @PeterKucirek for our next build of XTMF 1.3.

**Comment by bilalyusuf** [comment]
I've implemented a similar fix as Peters for the tool. It should be working now. unfortunately I could not replicate the problem when doing other strategy analyses. I will continue trying to update the tools as necessary to deal with the issue though
