### ISSUE TITLE
apply_batch_line_edits.py._LoadFile stores modifications as dictionary, leading to unexpected behaviour

### ISSUE THREAD

**Issue by bryce-sharman** [TravelModellingGroup/TMGToolbox#239]
The tool ApplyBatchLineEdits accepts text file showing a line filter(which is used in an Emme network calculation) and factors to apply to the line(s) headways and speeds.

The general format of the input file is 
    ```filter,[hdw factor, speed factor] (with the columns in the square brackets repeated for each time period```

The tool processed each line in turn, multiplying the network headway and speed by specified factors.

The issue is that the *_LoadFile* function saves the edits in a dictionary, producing unintuitive behaviour.

Say we have a the following lines then two operations are performed on line ```T117Aa```. The first multiplies the headway by 0.8 in all time periods while the second multiplies the speed by 1.09 in all time periods.
```
line=T117Aa,0.8,1,0.1,1,0.8,1,0.8,1,0.8,1
line=T117A_,1,1.09,1,1.09,1,1.09,1,1.09,1,1
```

The issue is that by storing as a dictionary, the subsequent instance of an exact filter overwrite previous definitions. Hence the following example will only multiply the speed by 1.09, *no headway changes are made*. This is different behaviour than we'd expect given that we can perform multiple changes on a line when wildcards are used.
```
line=T117Aa,0.8,1,0.1,1,0.8,1,0.8,1,0.8,1
line=T117Aa,1,1.09,1,1.09,1,1.09,1,1.09,1,1
```

The suggested fix is to store the changes as a list and not as a dictionary, and hence all lines will be stored allowing sequential changes to a set filter.

**Comment by JamesVaughan** [comment]
Good point, we had not considered the case where a line would be defined multiple times.  I'll code up a fix to this shortly.

**Comment by bryce-sharman** [comment]
Thanks James!

We ran into this issue for forecasts. Our base year run had one modification and then we tried to make a second scenario-based modification to a set of lines, which is when we came across this.
