### ISSUE TITLE
Shapes not being preserved in Generate Hypernetwork

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#30]
In Build 1.3.1177 (paired with Emme 4.3.2), shapes are not being preserved when the hypernetwork is created. To clarify, base links remain correct, but links in the hypernetwork are rendered as straight lines. Thankfully, correct length is preserved, so assignment results are still correct.

**Comment by JamesVaughan** [comment]
@mattaustin222 We are taking a look into this now.

**Comment by mattaustin222** [comment]
@bilalyusuf @JamesVaughan Any progress on this item?

**Comment by bilalyusuf** [comment]
I did some digging into this and according to the Inro API, EMME handles modifying link vertices slightly differently in 4.3.0+. I have tried testing some code that uses the new method but it wasn't working for all cases. I am exploring this further

**Comment by bilalyusuf** [comment]
I think I found the source of the problem and fixed it. it should be working now

**Comment by bilalyusuf** [comment]
the bug doesnt appear to have been fixed. will continue to do more work on it

**Comment by bilalyusuf** [comment]
The bug appears to be fixed now. The issue can be reopened if it still persists
