### ISSUE TITLE
Add additional function options in Import Network Package

### ISSUE THREAD

**Issue by bilalyusuf** [TravelModellingGroup/TMGToolbox#38]
The import network package should have the option to not add functions at all in addition to the function conflict option in the GUI.

**Comment by JamesVaughan** [comment]
This should be a good introduction into making a tool's GUI.

**Comment by PeterKucirek** [comment]
Like a `SKIP` option?

**Comment by lunaxi7** [comment]
No problem, I am looking into this.

**Comment by lunaxi7** [comment]
A skip option is added. By setting it as TRUE, the conflict options will not affect the functions in the current Emmebank. Please refer to the documentation web for [details](https://tmg.utoronto.ca/doc/1.6/tmgtoolbox/input_output/ImportNetworkPackage.html)
