### ISSUE TITLE
NWP round-trip is failing when exported from Emme 4.4.2

### ISSUE THREAD

**Issue by PeterKucirek** [TravelModellingGroup/TMGToolbox#44]
Looks like there is a bug in Emme's transit export tool/function, which causes a crash when batching in the result. So the export won't crash, but Emme isn't able to import the NWP. 

Furthermore, this is only catching certain edge cases. So far we've found two:
1. Lines without a description
2. Lines with an apostrophe in their name (e.g. O'Connor)

In case 1, the transit.221 file gets (note the two single apostrophe's next to each other):
`a'GB16Bb' g  12   0.01   0.01 ''                       65      0      0`

In case 2, the exporter write:
`a'T070Ab' b  12   0.01   0.01 "O'CONNOR A                 0      0      0"      0      0      0`

We've tested Emme 4.4.2 -> Emme 4.3.6 and 4.4.2 -> 4.4.2 as well.

@bryce-sharman has put together a testing procedure to forward to INRO to reproduce:
1.Copy scenario 5 to 98
2. Export all transit lines from scen 5
   a. comma separated
   b. Format values compatible with Emme transactions using engineering notation
3. Delete all transit lines in scenario 98
4. Process transit line transaction file into scenario 98

**Comment by lunaxi7** [comment]
We run into similar situations with a single quote in descriptions, and we used a grave accent to solve the issue. Although both Emme 4.3 and 4.4 use the single quote to enclose line descriptions, they are treating the same transit file differently. 

Here is what we found: 
- For Emme 4.3, the description can be empty or contain a single quote, it will not cause any trouble in importing/exporting. 
- For Emme 4.4, the empty description or those contain single quotes can be exported but not imported. An empty description will result in termination of importing in Emme 4.4; a description with a single quote will not terminate the importing but will cause missing line user data (ut1, ut2, ut3).

We will update the toolbox to accommodate this difference. The empty description will be replaced by a space and the single quote (') will be replaced by a grave accent (`) when exporting.

**Comment by lunaxi7** [comment]
Updates:
- Descriptions that are empty, have single quotes, and double quotes will be replaced by "No Description", grave accent(`), and spaces. 
- Add the option to export the NWP compatible with Emme 4.3 by trimming the description to be less than 20 characters (Emme 4.4 supports up to 120 characters).
