### ISSUE TITLE
Issues Importing NWP created in EMME 4.3 into EMME 4.4

### ISSUE THREAD

**Issue by rcaimano** [TravelModellingGroup/TMGToolbox#55]
I'm currently working at MTO with the System Analysis and Forecasting Office (SAFO) on the GGHM and am having issues importing a network package that was exported in EMME 4.3 into my EMME 4.4 project. I am using the latest version of the TMG toolbox with EMME 4.4 and get the following error message when running ImportNetwork Package:

![image](https://user-images.githubusercontent.com/3374238/87683016-87539600-c74e-11ea-8e6a-9cdbb5c15d56.png)

Below is a screenshot of the settings I used to import the package:
![image](https://user-images.githubusercontent.com/3374238/87686296-58d7ba00-c752-11ea-8ed4-8e3c101b1db8.png)
I've tried with the "Skip the merging of functions?" option on and off and ran into the same issue. Has anyone else run into this issue?

Let me know if there are any other details on my end that would help diagnose the error.

Here is the Traceback in case the screenshot above does not upload correctly:

> Traceback (most recent call last):
>   File "inro\director\tool\tool.py", line 127, in _run
>   File "C:\Users\rcaim\Downloads\TMGToolbox-dev-1.8\TMGToolbox\src\input_output\import_network_package.py", line 464, in run
>     self._execute()
>   File "C:\Users\rcaim\Downloads\TMGToolbox-dev-1.8\TMGToolbox\src\input_output\import_network_package.py", line 521, in _execute
>     self._batchin_lines(scenario, temp_folder, zf)
>   File "inro\director\logging\trail.py", line 271, in __trace
>   File "C:\Users\rcaim\Downloads\TMGToolbox-dev-1.8\TMGToolbox\src\input_output\import_network_package.py", line 579, in _batchin_lines
>     if self.transit_file_change is True:
> AttributeError: 'ImportNetworkPackage' object has no attribute 'transit_file_change'

Thanks!

**Comment by JamesVaughan** [comment]
@rcaimano if you could please pull the latest commit for dev-1.8.  It should resolve this issue.  In either case, could you please report back your findings.

Best regards,

James

**Comment by lunaxi7** [comment]
This issue has been solved. Please update the toolbox to allow the changes. Kindly us know if you have any questions.

**Comment by rcaimano** [comment]
I pulled the latest commit and ran it again but end up with a Format Error. See below:

![image](https://user-images.githubusercontent.com/3374238/87702171-0ead0380-c767-11ea-9d06-74fb048c69be.png)

It still seems to related to the transit lines.

**Comment by JamesVaughan** [comment]
@rcaimano it looks like there is an issue with the transit line transaction file in your NWP.  We would be happy to diagnose it for you if you can send it to us.  Please remember that any attached files here are publicly available.  If the network is sensitive please do not hesitate to instead send it to my address, James.Vaughan at utoronto dot ca.

**Comment by rcaimano** [comment]
@JamesVaughan I found the problem with the transit line file, the import worked now! Thank you for your help
