### ISSUE TITLE
Bug with Exporting Network Package 

### ISSUE THREAD

**Issue by hermanhuittc** [TravelModellingGroup/TMGToolbox#73]
Hi, I recently discovered a bug with the function to export network package.

When the transit lines transaction file is created, route descriptions with apostrophes (') are not properly quoted in single quotation marks. Therefore, when the network package file is imported again the process breaks at the reading of the transit lines transaction file.

For example, the route T070Gc in the GTA model has a route description of "O'CONNOR B". The first line of the route transaction should be output as:
a'T070Gc' b  16   9.82  15.29  'O'CONNOR B'              26      0   3.75

However, the toolbox outputs it as:
 a'T070Gc' b  16   9.82  15.29  O'CONNOR B                26      0   3.75

Thanks.

**Comment by JamesVaughan** [comment]
Thank you for the bug report.  If I could get some additional information, which version of the Toolbox are you currently using, and which versions of EMME both exported and imported this NWP?

**Comment by hermanhuittc** [comment]
The toolbox is the one released on 24 Jan 2020 for XTMF 1.7. The EMME used is of version 4.4.4.2.

**Comment by JamesVaughan** [comment]
We have implemented compatibility for EMME 4.4.4.2 in our current development branch.  I have just published a draft release with the latest changes that should be able to read in this NWP without issues at https://github.com/TravelModellingGroup/TMGToolbox/releases/tag/1.8-RC1.  This build is not be compatible with XTMF 1.7, so please make sure to include it second to XTMF 1.7's TMGToolbox. Please let me know if you continue to experience any issues.

**Comment by hermanhuittc** [comment]
Tried to export network package with v1.8, but it gave an error as in the screenshot below.

![image](https://user-images.githubusercontent.com/84792939/119551884-1ca8b900-bd68-11eb-9c1f-a7864d734e1c.png)

**Comment by JamesVaughan** [comment]
Thank you for finding this error.  I was able to reproduce it and have patched it in this release candidate.
https://github.com/TravelModellingGroup/TMGToolbox/releases/tag/1.8-RC2.  Please let us know if this resolves the issue.
